version: '3.1'

services:
  restapis:
    build:
      context: .
      dockerfile: ./apps/restapis/Dockerfile
      target: development
    command: pnpm run start:dev restapis
    env_file:
      - apps/restapis/.env
    ports:
      - '10003:10003'
    volumes:
      - .:/usr/src/app

  sockets:
    build:
      context: .
      dockerfile: ./apps/sockets/Dockerfile
      target: development
    command: pnpm run start:dev sockets
    env_file:
      - apps/sockets/.env
    ports:
      - '10001:10001'
    volumes:
      - .:/usr/src/app

  docdb:
    container_name: docdb
    image: redis:7.0-alpine
    ports:
      - "6379:6379" 
    networks:
      - intra

  rdb:
    container_name: rdb
    image: postgres
    ports:
      - "5432:5432" #http://localhost:5555
    environment:
      POSTGRES_USER: "pingpongdang"
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: "pingpong"
    volumes:
      - "/Users/myukang/goinfre/data/postgres:/var/lib/postgresql/data"
    networks:
      - intra

networks:
  intra:
    driver: bridge
